export enum MatchState {
  NOT_STARTED = "NOT_STARTED",
  TOSS = "TOSS",
  FIRST_INNINGS = "FIRST_INNINGS",
  INNINGS_BREAK = "INNINGS_BREAK",
  SECOND_INNINGS = "SECOND_INNINGS",
  COMPLETED = "COMPLETED",
}
